export const dataCityVN = [
    {
        name: "Hà Nội",
        slug: "ha-noi",
        type: "thanh-pho",
        name_with_type: "Thành phố Hà Nội",
        code: "3",
    },
    {
        name: "Hồ Chí Minh",
        slug: "ho-chi-minh",
        type: "thanh-pho",
        name_with_type: "Thành phố Hồ Chí Minh",
        code: "1",
    },
    {
        name: "Đà Nẵng",
        slug: "da-nang",
        type: "thanh-pho",
        name_with_type: "Thành phố Đà Nẵng",
        code: "4",
    },
    {
        name: "Cần Thơ",
        slug: "can-tho",
        type: "thanh-pho",
        name_with_type: "Thành phố Cần Thơ",
        code: "5",
    },
    {
        name: "Hải Phòng",
        slug: "hai-phong",
        type: "thanh-pho",
        name_with_type: "Thành phố Hải Phòng",
        code: "2",
    },
    {
        name: "An Giang",
        slug: "an-giang",
        type: "tinh",
        name_with_type: "Tỉnh An Giang",
        code: "58",
    },
    {
        name: "Bà Rịa - Vũng Tàu",
        slug: "ba-ria-vung-tau",
        type: "tinh",
        name_with_type: "Tỉnh Bà Rịa - Vũng Tàu",
        code: "7",
    },
    {
        name: "Bắc Giang",
        slug: "bac-giang",
        type: "tinh",
        name_with_type: "Tỉnh Bắc Giang",
        code: "33",
    },
    {
        name: "Bắc Kạn",
        slug: "bac-kan",
        type: "tinh",
        name_with_type: "Tỉnh Bắc Kạn",
        code: "29",
    },
    {
        name: "Bạc Liêu",
        slug: "bac-lieu",
        type: "tinh",
        name_with_type: "Tỉnh Bạc Liêu",
        code: "62",
    },
    {
        name: "Bắc Ninh",
        slug: "bac-ninh",
        type: "tinh",
        name_with_type: "Tỉnh Bắc Ninh",
        code: "6",
    },
    {
        name: "Bến Tre",
        slug: "ben-tre",
        type: "tinh",
        name_with_type: "Tỉnh Bến Tre",
        code: "54",
    },
    {
        name: "Bình Định",
        slug: "binh-dinh",
        type: "tinh",
        name_with_type: "Tỉnh Bình Định",
        code: "45",
    },
    {
        name: "Bình Dương",
        slug: "binh-duong",
        type: "tinh",
        name_with_type: "Tỉnh Bình Dương",
        code: "8",
    },
    {
        name: "Bình Phước",
        slug: "binh-phuoc",
        type: "tinh",
        name_with_type: "Tỉnh Bình Phước",
        code: "19",
    },
    {
        name: "Bình Thuận",
        slug: "binh-thuan",
        type: "tinh",
        name_with_type: "Tỉnh Bình Thuận",
        code: "48",
    },
    {
        name: "Cà Mau",
        slug: "ca-mau",
        type: "tinh",
        name_with_type: "Tỉnh Cà Mau",
        code: "63",
    },
    {
        name: "Cao Bằng",
        slug: "cao-bang",
        type: "tinh",
        name_with_type: "Tỉnh Cao Bằng",
        code: "28",
    },
    {
        name: "Đắk Lắk",
        slug: "dak-lak",
        type: "tinh",
        name_with_type: "Tỉnh Đắk Lắk",
        code: "51",
    },
    {
        name: "Đắk Nông",
        slug: "dak-nong",
        type: "tinh",
        name_with_type: "Tỉnh Đắk Nông",
        code: "52",
    },
    {
        name: "Điện Biên",
        slug: "dien-bien",
        type: "tinh",
        name_with_type: "Tỉnh Điện Biên",
        code: "35",
    },
    {
        name: "Đồng Nai",
        slug: "dong-nai",
        type: "tinh",
        name_with_type: "Tỉnh Đồng Nai",
        code: "10",
    },
    {
        name: "Đồng Tháp",
        slug: "dong-thap",
        type: "tinh",
        name_with_type: "Tỉnh Đồng Tháp",
        code: "57",
    },
    {
        name: "Gia Lai",
        slug: "gia-lai",
        type: "tinh",
        name_with_type: "Tỉnh Gia Lai",
        code: "50",
    },
    {
        name: "Hà Giang",
        slug: "ha-giang",
        type: "tinh",
        name_with_type: "Tỉnh Hà Giang",
        code: "27",
    },
    {
        name: "Hà Nam",
        slug: "ha-nam",
        type: "tinh",
        name_with_type: "Tỉnh Hà Nam",
        code: "23",
    },
    {
        name: "Hà Tĩnh",
        slug: "ha-tinh",
        type: "tinh",
        name_with_type: "Tỉnh Hà Tĩnh",
        code: "41",
    },
    {
        name: "Hải Dương",
        slug: "hai-duong",
        type: "tinh",
        name_with_type: "Tỉnh Hải Dương",
        code: "21",
    },
    {
        name: "Hậu Giang",
        slug: "hau-giang",
        type: "tinh",
        name_with_type: "Tỉnh Hậu Giang",
        code: "60",
    },
    {
        name: "Hòa Bình",
        slug: "hoa-binh",
        type: "tinh",
        name_with_type: "Tỉnh Hòa Bình",
        code: "38",
    },
    {
        name: "Hưng Yên",
        slug: "hung-yen",
        type: "tinh",
        name_with_type: "Tỉnh Hưng Yên",
        code: "22",
    },
    {
        name: "Khánh Hòa",
        slug: "khanh-hoa",
        type: "tinh",
        name_with_type: "Tỉnh Khánh Hòa",
        code: "15",
    },
    {
        name: "Kiên Giang",
        slug: "kien-giang",
        type: "tinh",
        name_with_type: "Tỉnh Kiên Giang",
        code: "59",
    },
    {
        name: "Kon Tum",
        slug: "kon-tum",
        type: "tinh",
        name_with_type: "Tỉnh Kon Tum",
        code: "49",
    },
    {
        name: "Lai Châu",
        slug: "lai-chau",
        type: "tinh",
        name_with_type: "Tỉnh Lai Châu",
        code: "36",
    },
    {
        name: "Lâm Đồng",
        slug: "lam-dong",
        type: "tinh",
        name_with_type: "Tỉnh Lâm Đồng",
        code: "18",
    },
    {
        name: "Lạng Sơn",
        slug: "lang-son",
        type: "tinh",
        name_with_type: "Tỉnh Lạng Sơn",
        code: "32",
    },
    {
        name: "Lào Cai",
        slug: "lao-cai",
        type: "tinh",
        name_with_type: "Tỉnh Lào Cai",
        code: "16",
    },
    {
        name: "Long An",
        slug: "long-an",
        type: "tinh",
        name_with_type: "Tỉnh Long An",
        code: "13",
    },
    {
        name: "Nam Định",
        slug: "nam-dinh",
        type: "tinh",
        name_with_type: "Tỉnh Nam Định",
        code: "24",
    },
    {
        name: "Nghệ An",
        slug: "nghe-an",
        type: "tinh",
        name_with_type: "Tỉnh Nghệ An",
        code: "40",
    },
    {
        name: "Ninh Bình",
        slug: "ninh-binh",
        type: "tinh",
        name_with_type: "Tỉnh Ninh Bình",
        code: "26",
    },
    {
        name: "Ninh Thuận",
        slug: "ninh-thuan",
        type: "tinh",
        name_with_type: "Tỉnh Ninh Thuận",
        code: "47",
    },
    {
        name: "Phú Thọ",
        slug: "phu-tho",
        type: "tinh",
        name_with_type: "Tỉnh Phú Thọ",
        code: "34",
    },
    {
        name: "Phú Yên",
        slug: "phu-yen",
        type: "tinh",
        name_with_type: "Tỉnh Phú Yên",
        code: "46",
    },
    {
        name: "Quảng Bình",
        slug: "quang-binh",
        type: "tinh",
        name_with_type: "Tỉnh Quảng Bình",
        code: "42",
    },
    {
        name: "Quảng Nam",
        slug: "quang-nam",
        type: "tinh",
        name_with_type: "Tỉnh Quảng Nam",
        code: "17",
    },
    {
        name: "Quảng Ngãi",
        slug: "quang-ngai",
        type: "tinh",
        name_with_type: "Tỉnh Quảng Ngãi",
        code: "20",
    },
    {
        name: "Quảng Ninh",
        slug: "quang-ninh",
        type: "tinh",
        name_with_type: "Tỉnh Quảng Ninh",
        code: "9",
    },
    {
        name: "Quảng Trị",
        slug: "quang-tri",
        type: "tinh",
        name_with_type: "Tỉnh Quảng Trị",
        code: "43",
    },
    {
        name: "Sóc Trăng",
        slug: "soc-trang",
        type: "tinh",
        name_with_type: "Tỉnh Sóc Trăng",
        code: "61",
    },
    {
        name: "Sơn La",
        slug: "son-la",
        type: "tinh",
        name_with_type: "Tỉnh Sơn La",
        code: "37",
    },
    {
        name: "Tây Ninh",
        slug: "tay-ninh",
        type: "tinh",
        name_with_type: "Tỉnh Tây Ninh",
        code: "14",
    },
    {
        name: "Thái Bình",
        slug: "thai-binh",
        type: "tinh",
        name_with_type: "Tỉnh Thái Bình",
        code: "25",
    },
    {
        name: "Thái Nguyên",
        slug: "thai-nguyen",
        type: "tinh",
        name_with_type: "Tỉnh Thái Nguyên",
        code: "12",
    },
    {
        name: "Thanh Hóa",
        slug: "thanh-hoa",
        type: "tinh",
        name_with_type: "Tỉnh Thanh Hóa",
        code: "39",
    },
    {
        name: "Thừa Thiên Huế",
        slug: "thua-thien-hue",
        type: "tinh",
        name_with_type: "Tỉnh Thừa Thiên Huế",
        code: "44",
    },
    {
        name: "Tiền Giang",
        slug: "tien-giang",
        type: "tinh",
        name_with_type: "Tỉnh Tiền Giang",
        code: "53",
    },
    {
        name: "Trà Vinh",
        slug: "tra-vinh",
        type: "tinh",
        name_with_type: "Tỉnh Trà Vinh",
        code: "55",
    },
    {
        name: "Tuyên Quang",
        slug: "tuyen-quang",
        type: "tinh",
        name_with_type: "Tỉnh Tuyên Quang",
        code: "30",
    },
    {
        name: "Vĩnh Long",
        slug: "vinh-long",
        type: "tinh",
        name_with_type: "Tỉnh Vĩnh Long",
        code: "56",
    },
    {
        name: "Vĩnh Phúc",
        slug: "vinh-phuc",
        type: "tinh",
        name_with_type: "Tỉnh Vĩnh Phúc",
        code: "11",
    },
    {
        name: "Yên Bái",
        slug: "yen-bai",
        type: "tinh",
        name_with_type: "Tỉnh Yên Bái",
        code: "31",
    },
];
